<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="RUN ON EDGE"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="28,347">
  <properties />
            <testcase name="TC_02_Login_To_System" time="24,324" classname="com.bankguru.user.Level_15_Log_Report_HTML">
                <failure type="java.lang.AssertionError"
                  message="expected [Welcome To Manager&apos;s Page of Guru99 Bank.] but found [Welcome To Manager&apos;s Page of Guru99 Bank]"
              >
<![CDATA[java.lang.AssertionError: expected [Welcome To Manager's Page of Guru99 Bank.] but found [Welcome To Manager's Page of Guru99 Bank]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:442)
  commons.AbstractTest.checkEquals(AbstractTest.java:518)
  commons.AbstractTest.verifyEquals(AbstractTest.java:528)
  com.bankguru.user.Level_15_Log_Report_HTML.TC_02_Login_To_System(Level_15_Log_Report_HTML.java:131)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.TestNG.privateMain(TestNG.java:1354)
  org.testng.TestNG.main(TestNG.java:1323)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_01_Register_To_System" time="4,023" classname="com.bankguru.user.Level_15_Log_Report_HTML" />
      
</testsuite>
